# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gomod"
    schedule: { interval: "weekly" }
    directory: "/"

  - package-ecosystem: "gomod"
    schedule: { interval: "weekly" }
    directory: "/examples/config"

  - package-ecosystem: "gomod"
    schedule: { interval: "weekly" }
    directory: "/examples/logging"

  - package-ecosystem: "gomod"
    schedule: { interval: "weekly" }
    directory: "/examples/mq"

  - package-ecosystem: "gomod"
    schedule: { interval: "weekly" }
    directory: "/examples/jwe"
