---
type: yml
parent1:
  name: parent1
  id: 1234
  child1:
    name: child1
    type: yml
    grandchild1:
      ids:
        - 1
        - 2
        - 3
      "on": true
    empty: { }
  str_map:
    key1: val1
    key2: val2
    key3: val3
  str_list_map:
    key1:
      - val1
      - val2
      - val3
    key2:
      - val4
      - val5
  int_map:
    key1: 1
    key2: 1
    key3: 1
  float_map:
    key1: 1.1
    key2: 1.2
    key3: 1.3
  bool_map:
    ok1: true
    ok2: true
    ok3_not: false
parent2:
  name: parent2
  id: 5678
  child2:
    name: child2
    grandchild2:
      ids:
        - 4
        - 5
        - 6
      "on": true
    empty: { }
booleans:
  - true
  - false
  - true
int_booleans:
  - 1
  - 0
  - 1
str_booleans:
  - "1"
  - t
  - f
str_bool: "1"
time: "2019-01-01"
duration: "3s"
negative_int: -1234
orphan:
  - red
  - blue
  - orange
empty: { }


---
type: yaml
empty: { }
