## Require Docker Engine release 18.06.0+
version: "3.7"

networks: { proxy: { external: true, name: proxy } }

services:
  example-postgres:
    container_name: example-postgres
    hostname: postgres
    image: postgres:13.12-alpine
    restart: unless-stopped
    user: root
    read_only: true
    logging: { driver: local, options: { max-size: 32m, max-file: 16 } }
    tmpfs: [ /tmp ]
    volumes:
      - "postgres/run:/var/run/postgresql"
      - "postgres/data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=example"
      - "POSTGRES_USER=example"
      - "POSTGRES_PASSWORD=Example#123789"
    ports:
      - "5432:5432"
    networks: { proxy: { } }
  # example-postgres ##########################################################
# services
